name: flutter_app435
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - image/menu_item_1.png
    - image/menu_item_2.png
    - image/menu_item_3.png
    - image/menu_item_4.png
  uses-material-design: true
